# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'WrkplanPayroll' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WrkplanPayroll
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'KRProgressHUD'
pod 'ReachabilitySwift'
pod 'Toast-Swift', '~> 5.0.0'
pod 'FSCalendar'
pod 'DropDown'
pod 'IQKeyboardManagerSwift'
pod 'lottie-ios'
#pod 'iOSDropDown'

  target 'WrkplanPayrollTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WrkplanPayrollUITests' do
    # Pods for testing
  end

end


post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
