# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WrkplanPayroll' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WrkplanPayroll
  pod 'Alamofire'
pod 'SwiftyJSON'
pod 'KRProgressHUD'
pod 'ReachabilitySwift'
pod 'Toast-Swift', '~> 5.0.0'
pod 'FSCalendar'
pod 'DropDown'
#pod 'iOSDropDown'

  target 'WrkplanPayrollTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WrkplanPayrollUITests' do
    # Pods for testing
  end

end
